services:
  postgres:
    image: mysql:8.0
    container_name: base_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: base_redis_stories
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes ${REDIS_PASSWORD:+--requirepass ${REDIS_PASSWORD}}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}

volumes:
  mysql_data:
