version: '3.8'
services:
  app:
    image: binhxikeno2/story-be:latest
    container_name: story-be-app
    ports:
      - '3003:3003'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        labels: 'service=story-be'
    volumes:
      - ./logs:/src/logs
    environment:
      - NODE_ENV=production
      - LOG_CONSOLE=true
