name: CD
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup env
        run: |
          touch .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "TZ=${{ secrets.TZ }}" >> .env
          echo "LOG_CONSOLE=${{ secrets.LOG_CONSOLE }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "API_DOC_STATUS=${{ secrets.API_DOC_STATUS }}" >> .env
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env
          echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "TARGET_CRAWL_HOST=${{ secrets.TARGET_CRAWL_HOST }}" >> .env
          echo "RAPIDGATOR_USERNAME=${{ secrets.RAPIDGATOR_USERNAME }}" >> .env
          echo "RAPIDGATOR_PASSWORD=${{ secrets.RAPIDGATOR_PASSWORD }}" >> .env
          echo "RAPIDGATOR_DOWNLOAD_PATH=${{ secrets.RAPIDGATOR_DOWNLOAD_PATH }}" >> .env
          echo "SCRAPPY_KEY_API=${{ secrets.SCRAPPY_KEY_API }}" >> .env
          echo "HETZNER_S3_ACCESS_KEY=${{ secrets.HETZNER_S3_ACCESS_KEY }}" >> .env
          echo "HETZNER_S3_SECRET_KEY=${{ secrets.HETZNER_S3_SECRET_KEY }}" >> .env
          echo "HETZNER_S3_ENDPOINT=${{ secrets.HETZNER_S3_ENDPOINT }}" >> .env
          echo "HETZNER_S3_BUCKET=${{ secrets.HETZNER_S3_BUCKET }}" >> .env
          echo "HETZNER_S3_REGION=${{ secrets.HETZNER_S3_REGION }}" >> .env
          echo "X_API_KEY_WP=${{ secrets.X_API_KEY_WP }}" >> .env
          echo "API_WP_URL=${{ secrets.API_WP_URL }}" >> .env


          echo "âœ… Environment file created successfully"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        run: |
          docker build --no-cache -t app:latest .
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image to Container Registry
        run: |
          docker tag app:latest binhxikeno2/story-be:latest
          docker push binhxikeno2/story-be:latest
      - name: Send portainer webhook
        run: |
          curl --insecure --connect-timeout 60 -X POST ${{ secrets.PORTAINER_STACK_WEBHOOK }}
