name: CD
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup env
        run: |
          touch .env
          echo "NEXT_PUBLIC_API_URL=${{ secrets.PORT }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.TZ }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.LOG_CONSOLE }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.NODE_ENV }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.API_DOC_STATUS }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.MYSQL_HOST }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.MYSQL_PORT }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.MYSQL_USER }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.TARGET_CRAWL_HOST }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.RAPIDGATOR_USERNAME }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.RAPIDGATOR_PASSWORD }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.RAPIDGATOR_DOWNLOAD_PATH }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.SCRAPPY_KEY_API }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.HETZNER_S3_ACCESS_KEY }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.HETZNER_S3_SECRET_KEY }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.HETZNER_S3_ENDPOINT }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.HETZNER_S3_BUCKET }}" >> .env
          echo "NEXT_PUBLIC_MODE=${{ secrets.HETZNER_S3_REGION }}" >> .env
         cat .env

          echo "âœ… Environment file created successfully"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        run: |
          docker build --no-cache -t app:latest .
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image to Container Registry
        run: |
          docker tag app:latest binhxikeno2/story-be:latest
          docker push binhxikeno2/story-be:latest
      - name: Send portainer webhook
        run: |
          curl --insecure --connect-timeout 60 -X POST ${{ secrets.PORTAINER_STACK_WEBHOOK }}
